const capitalsToCountries = {
  "Kuwait City": "Kuwait",
  "Washington D.C.": "United States",
  Ottawa: "Canada",
  "Mexico City": "Mexico",
  Brasilia: "Brazil",
  "Buenos Aires": "Argentina",
  Santiago: "Chile",
  Berlin: "Germany",
  Paris: "France",
  Madrid: "Spain",
  Rome: "Italy",
  London: "United Kingdom",
  Moscow: "Russia",
  Canberra: "Australia",
  Beijing: "China",
  "Addis Ababa":"Ethiopia",
  "New Delhi": "India",
  Tokyo: "Japan",
  Seoul: "South Korea",
  Pretoria: "South Africa",
  Cairo: "Egypt",
  Abuja: "Nigeria",
  Nairobi: "Kenya",
  Riyadh: "Saudi Arabia",
  "Abu Dhabi": "United Arab Emirates",
  Ankara: "Turkey",
  Athens: "Greece",
  Stockholm: "Sweden",
  Oslo: "Norway",
  Helsinki: "Finland",
  Copenhagen: "Denmark",
  Brussels: "Belgium",
  Amsterdam: "Netherlands",
  Warsaw: "Poland",
  Kyiv: "Ukraine",
  "Nur-Sultan": "Kazakhstan",
  Tashkent: "Uzbekistan",
  Ashgabat: "Turkmenistan",
  Kabul: "Afghanistan",
  Islamabad: "Pakistan",
  Colombo: "Sri Lanka",
  Dhaka: "Bangladesh",
  Kathmandu: "Nepal",
  Thimphu: "Bhutan",
  Ulaanbaatar: "Mongolia",
  Tehran: "Iran",
  Baghdad: "Iraq",
  Jerusalem: "Palestine",
  Beirut: "Lebanon",
  Amman: "Jordan",
  Damascus: "Syria",
  Tripoli: "Libya",
  Rabat: "Morocco",
  Tunis: "Tunisia",
  Tirana: "Albania",
  Algiers: "Algeria",
  "Andorra la Vella": "Andorra",
  Luanda: "Angola",
  "Saint John's": "Antigua and Barbuda",
  Yerevan: "Armenia",
  Vienna: "Austria",
  Baku: "Azerbaijan",
  Nassau: "Bahamas",
  Manama: "Bahrain",
  Bridgetown: "Barbados",
  Minsk: "Belarus",
  Belmopan: "Belize",
  "Porto-Novo": "Benin",
  Sucre: "Bolivia",
  Sarajevo: "Bosnia and Herzegovina",
  Gaborone: "Botswana",
  "Bandar Seri Begawan": "Brunei",
  Sofia: "Bulgaria",
  Ouagadougou: "Burkina Faso",
  Bujumbura: "Burundi",
  Praia: "Cape Verde",
  "Phnom Penh": "Cambodia",
  Yaoundé: "Cameroon",
  Bangui: "Central African Republic",
  "N'Djamena": "Chad",
  Moroni: "Comoros",
  Kinshasa: "Democratic Republic of the Congo",
  Brazzaville: "Republic of the Congo",
  "San José": "Costa Rica",
  Zagreb: "Croatia",
  Havana: "Cuba",
  Nicosia: "Cyprus",
  Prague: "Czech Republic",
  Djibouti: "Djibouti",
  Roseau: "Dominica",
  "Santo Domingo": "Dominican Republic",
  Dili: "East Timor",
  Quito: "Ecuador",
  "San Salvador": "El Salvador",
  Malabo: "Equatorial Guinea",
  Asmara: "Eritrea",
  Tallinn: "Estonia",
  Mbabane: "Eswatini",
  Suva: "Fiji",
  Libreville: "Gabon",
  Banjul: "Gambia",
  Tbilisi: "Georgia",
  Accra: "Ghana",
  "St. George's": "Grenada",
  "Guatemala City": "Guatemala",
  Conakry: "Guinea",
  Bissau: "Guinea-Bissau",
  Georgetown: "Guyana",
  "Port-au-Prince": "Haiti",
  Tegucigalpa: "Honduras",
  Budapest: "Hungary",
  Reykjavik: "Iceland",
  Jakarta: "Indonesia",
  Dublin: "Ireland",
  Kingston: "Jamaica",
  Tarawa: "Kiribati",
  Pristina: "Kosovo",
  Bishkek: "Kyrgyzstan",
  Vientiane: "Laos",
  Riga: "Latvia",
  Maseru: "Lesotho",
  Monrovia: "Liberia",
  Vaduz: "Liechtenstein",
  Vilnius: "Lithuania",
  "Luxembourg City": "Luxembourg",
  Antananarivo: "Madagascar",
  Lilongwe: "Malawi",
  Malé: "Maldives",
  Bamako: "Mali",
  Valletta: "Malta",
  Majuro: "Marshall Islands",
  Nouakchott: "Mauritania",
  "Port Louis": "Mauritius",
  Palikir: "Micronesia",
  Chisinau: "Moldova",
  Monaco: "Monaco",
  Podgorica: "Montenegro",
  Maputo: "Mozambique",
  Naypyidaw: "Myanmar",
  Windhoek: "Namibia",
  "Yaren District": "Nauru",
  Managua: "Nicaragua",
  Niamey: "Niger",
  Pyongyang: "North Korea",
  Skopje: "North Macedonia",
  Ngerulmud: "Palau",
  "Panama City": "Panama",
  "Port Moresby": "Papua New Guinea",
  Asunción: "Paraguay",
  muscat:"oman",
  Lima: "Peru",
  Manila: "Philippines",
  Lisbon: "Portugal",
  Doha: "Qatar",
  Bucharest: "Romania",
  Kigali: "Rwanda",
  Basseterre: "Saint Kitts and Nevis",
  Castries: "Saint Lucia",
  Kingstown: "Saint Vincent and the Grenadines",
  Apia: "Samoa",
  "San Marino": "San Marino",
  "São Tomé": "São Tomé and Príncipe",
  Dakar: "Senegal",
  Belgrade: "Serbia",
  Victoria: "Seychelles",
  Freetown: "Sierra Leone",
  Singapore: "Singapore",
  Bratislava: "Slovakia",
  Ljubljana: "Slovenia",
  Honiara: "Solomon Islands",
  Mogadishu: "Somalia",
  Juba: "South Sudan",
  Khartoum: "Sudan",
  Paramaribo: "Suriname",
  Bern: "Switzerland",
  Dushanbe: "Tajikistan",
  Dodoma: "Tanzania",
  Bangkok: "Thailand",
  Lomé: "Togo",
  Nukuʻalofa: "Tonga",
  "Port of Spain": "Trinidad and Tobago",
  Funafuti: "Tuvalu",
  Kampala: "Uganda",
  Montevideo: "Uruguay",
  "Port Vila": "Vanuatu",
  "Vatican City": "Vatican City",
  Caracas: "Venezuela",
  "Sana'a": "Yemen",
  "sanaa":"yemen",
  Lusaka: "Zambia",
  Harare: "Zimbabwe",
  "Bogotá ": "Colombia",
  Dubai: "United Arab Emirates",
  Zurich: "Switzerland",
  Hanoi: "Vietnam",
  "Kuala Lumpur": "Malaysia",
  nuuk: "greenland",
};

export default function getCountryByCapital(
  capital: string
): string | undefined {
  const capitalLowerCase = capital.toLowerCase();
  for (let key in capitalsToCountries) {
    if (key.toLowerCase() === capitalLowerCase) {
      return capitalsToCountries[key as keyof typeof capitalsToCountries];
    }
  }
  return undefined;
}

console.log(getCountryByCapital("Paris")); // Output: France
console.log(getCountryByCapital("Tokyo")); // Output: Japan
